
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Franki's Junkyard
email: francescapham5055@gmail.com
description: >- 
  Welcome to my junkyard! This static site was made using Jekyll and Github pages.
  Go ahead! Explore my journey and see how far I grown!
baseurl: "" 
url: "https:/madeem-delvi.github.io" 
permalink: /:categories/:title/
twitter_username: 
github_username: madeem-delvi 

theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
